-- find all address_id of addresses in the city of Dundee
-- use INNER JOIN FROM address on to city

-- SELECT
-- *    
-- FROM
--     address
--     INNER JOIN
--     city
--     ON
--     city.city = address.address_id
--     WHERE
--     city_id = Dundee