-- find all address_id of addresses in the city of Dundee
-- use INNER JOIN FROM address on to city

-- SELECT
--     address.city_id
--     FROM
--     address
--     INNER JOIN
--     city
--     ON
--     city = address_id;